---
  # Install isc-dhcp-server
- name: Install isc-dhcp-server
  with_items:
    - isc-dhcp-server
  apt: name={{ item }} state=present

  # Set desired permissions on /etc/dhcp or use defaults
- name: Set permissions on /etc/dhcp
  file: path=/etc/dhcp state=directory mode={{ dhcp_dir_mode | default("0750") }}

  # Generate configuration
- name: Generate dhcpd.conf
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf owner=root group=root mode=0644 validate='/usr/sbin/dhcpd -t -cf %s'

  # Generate configuration interfaces 
- name: Generate configuration interfaces 
  template: src=isc-dhcp-server.j2 dest=/etc/default/isc-dhcp-server owner=root group=root mode=0644 

  # Enable DHCP server
- name: Start the dhcp services DHCP
  service: name=isc-dhcp-server state=restarted enabled=yes
        